name: swipeable
description: >
  A widget that emits events when swiped past a threshold. Can be used to add
  quick actions for ListTiles.

version: 1.0.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
